/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "secondary-dim": "#5c5241",
              "outline": "#797c73",
              "on-error-container": "#752121",
              "surface-bright": "#fbf9f4",
              "outline-variant": "#b1b3a9",
              "error": "#9f403d",
              "background": "#fbf9f4",
              "primary-dim": "#535252",
              "on-secondary-fixed": "#483e2e",
              "surface": "#fbf9f4",
              "secondary": "#695d4c",
              "on-secondary-fixed-variant": "#655a49",
              "error-dim": "#4e0309",
              "tertiary-fixed-dim": "#e7e5e4",
              "secondary-container": "#f0e0ca",
              "primary-fixed-dim": "#d6d4d3",
              "on-secondary": "#fff8f1",
              "inverse-surface": "#0e0e0c",
              "on-surface": "#31332c",
              "on-background": "#31332c",
              "surface-container-high": "#e8e9e0",
              "tertiary-container": "#f6f3f2",
              "surface-container": "#efeee6",
              "secondary-fixed": "#f0e0ca",
              "primary-fixed": "#e5e2e1",
              "primary-container": "#e5e2e1",
              "on-tertiary-fixed": "#4a4949",
              "on-secondary-container": "#5b5040",
              "on-tertiary": "#fbf8f8",
              "surface-variant": "#e2e3d9",
              "surface-container-highest": "#e2e3d9",
              "tertiary": "#5f5f5f",
              "error-container": "#fe8983",
              "on-primary-fixed-variant": "#5c5b5b",
              "on-primary-container": "#525151",
              "secondary-fixed-dim": "#e2d2bd",
              "on-surface-variant": "#5e6058",
              "tertiary-fixed": "#f6f3f2",
              "surface-container-lowest": "#ffffff",
              "primary": "#5f5e5e",
              "on-tertiary-fixed-variant": "#676666",
              "on-tertiary-container": "#5c5b5b",
              "surface-dim": "#d9dbcf",
              "surface-tint": "#5f5e5e",
              "on-primary-fixed": "#403f3f",
              "surface-container-low": "#f5f4ed",
              "inverse-on-surface": "#9e9d99",
              "inverse-primary": "#ffffff",
              "on-primary": "#faf7f6",
              "tertiary-dim": "#535353",
              "on-error": "#fff7f6"
      },
      "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
      },
      "fontFamily": {
              "headline": ["Noto Serif", "serif"],
              "body": ["Inter", "sans-serif"],
              "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
